### ISSUE TITLE
Dungeons can't go over level 100

### ISSUE THREAD

**Issue by jimnvox** [TheSench/SIMSpellstone#21]
I assume this has to do with the way the data gets pulled in during the auto-updates, it seems that the 'upgrade_levels' property of all the dungeons gets set to 100, which looks to be coming directly from the api.php data (?) 'dungeon_upgrade_levels' which is set at 100 for some reason on synapticon's end.

Not positive that this is what triggers the error when trying to setup against a dungeon past level 100, but without exploring deeper I'm guessing that's the cause for the following error when a level past 100 is input:

simulator.js:2413 Uncaught TypeError: Cannot read property 'maxLevel' of undefined
    at getPresetUnit (simulator.js:2413)
    at load_preset_deck (simulator.js:2288)
    at load_deck_raid (simulator.js:2263)
    at HTMLInputElement.<anonymous> (simulator.js:6949)
    at HTMLInputElement.dispatch (vendor.js:3)
    at HTMLInputElement.r.handle (vendor.js:3)

**Comment by jimnvox** [comment]
I've confirmed that just by changing the 'upgrade_levels' property in data.min.js to a larger number I can get rid of the error.  Did not confirm that the deck or simulation behaved as expected, but this points to my suspicions above.

**Comment by TheSench** [comment]
They cap at 100 because the units are all max-upgraded by then.  After 100, the dungeon just scales stats.  I tracked down the bug in the code that was causing this - it was around random units once they are max-leveled.  It should be fixed now.

**Comment by jimnvox** [comment]
Yessir. I can see that now.  Which is why my "fix" mentioned above didn't fix anything when I actually went to sim against varied decks for the dungeon.

Thanks!
